### PR TITLE
Darkened svgs to match devtool icon colors

### PR DESCRIPTION
**Pull request by helenvholmes**
The icons in-tree have a specific color so they can do light and dark them with a CSS filter swap, but this should do for the demo.

### CODE REVIEW

**Comment by jlongster** [comment]
Yay!

**Comment by jasonLaster** [comment]
Thanks! Mind attaching screenshots in the future so I can  provide timely feedback.

**Comment by jasonLaster** [comment]
It's tough to look at CSS and svg changes and see what changed

**Comment by helenvholmes** [comment]
@jasonLaster can do! 👍

**Pull request merged**
