### PR TITLE
improve the advanced section of the README

### PR DESCRIPTION
**Pull request by clarkbw**
Added a definition section for the environment variable
Linked to the sample file
Added a NOTE about the the gecko source

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks, much better.

**Comment by jlongster** [comment]
Yeah very cool. If I merge this it will likely conflict with the other PR. Let's get that one in first because it's from a contributor?

**Comment by clarkbw** [comment]
> Let's get that one in first

Agreed, I'll rebase once the other one lands.

**Comment by jlongster** [comment]
Looks like this can still be merged actually. I'll merge it.

**Pull request merged**
