### PR TITLE
Alphabetized + two-space'd, #9

### PR DESCRIPTION
**Pull request by helenvholmes**

### CODE REVIEW

**Comment by jasonLaster** [comment]
:smiley_cat: 

can we lint for this stuff going forward?

**Comment by jlongster** [comment]
I don't know much about CSS linting, but the devtools doesn't have that. We can do it for our project thought

**Comment by helenvholmes** [comment]
The reason I understood we don't have CSS-linting in devtools isn't that it's not a good idea, but hat it would both take time to implement and that it would be going off like crazy in our highly specific, XUL/CSS world.

Projects like this will make CSS-linting more and more possible, so I think we should use it.

**Comment by jlongster** [comment]
Yay!

**Pull request merged**
