### PR TITLE
merge in ff-devtools-libs

### PR DESCRIPTION
**Pull request by jlongster**
Let's see what fails....

### CODE REVIEW

**Comment by jlongster** [comment]
@jasonLaster might need some help looking into these testing issues, I can't reproduce the cypress one and the karma one is a little mysterious to me

**Comment by jasonLaster** [comment]
Looks good. 

Sorry, I didn't realize this PR was ready for review.

**Comment by jasonLaster** [comment]
Merging as circle is failing to launch Firefox. I discussed this in the other PR :/ we can investigate later. Also this is a merge conflict waiting I happen

**Comment by jasonLaster** [comment]
Actually can't merge because there are conflicts.

**Comment by jlongster** [comment]
Same errors as before, so merging now.

**Pull request merged**
