### PR TITLE
Rewrite of the README (WIP)

### PR DESCRIPTION
**Pull request by clarkbw**
(don't merge this yet, I need to update the contributions page to match)

no screenshots yet, those may come
focused on a headline, getting started, getting involved, and getting in contact

### CODE REVIEW

**Comment by clarkbw** [comment]
Meant to add `[ci skip]` to the commit

**Comment by clarkbw** [comment]
README screenshot
screen shot 2016-07-15 at 14 33 43

**Comment by jlongster** [comment]
This looks great, I thought you wanted to move some of those instructions for getting debuggees running to a separate doc? I'm OK with that if you want to.

This looks awesome though!

**Comment by clarkbw** [comment]
> move some of those instructions for getting debuggees running to a separate doc?

Yes, and It still looks too large, but I wanted to have the basic instructions available for people.  I'm looking at moving it to the "empty page" where its likely more useful.  "Here's how to get Chrome running"  And if I make a linkable doc like you suggested I think we can link to help getting debug targets running.

**Comment by jasonLaster** [comment]
Looks great. +1 on a doc for debug targets and utilizing the empty page.

**Comment by jasonLaster** [comment]
Couple comments

+ Top section should include chrome debug protocol
+ Top section should include npm aswell as GitHub. Npm makes it embeddable.

**Comment by jlongster** [comment]
Right now, we should explicitly state that Firefox is the only officially supported version I think, but it'd be fine to say "experimental" support for Chrome protocol (or something like that). We aren't quite in the phase where we can support multiple protocols because we're time-constrained and still building basic features.

**Comment by clarkbw** [comment]
Trying to build some assets to help explain certain things.

debugger - web browser

**Comment by jasonLaster** [comment]
@clarkbw nice idea

@jlongster agreed. The "experimental" language makes sense there

**Comment by jasonLaster** [comment]
ping @clarkbw any progress? Also, happy to help land this if you can break it up into smaller tickets

**Comment by clarkbw** [comment]
Ok, bunch of changes.  This is probably good to land for now as I've filed another issue for the default page and can make smaller updates to the docs later.

**Comment by jasonLaster** [comment]
:+1:

**Comment by jasonLaster** [comment]
@jlongster if you have any comments on the docs, it should be pretty easy for anyone to open a small pr on top of this

**Pull request merged**
