### PR TITLE
Add increment example

### PR DESCRIPTION
**Pull request by jasonLaster**
This is a good example of a page that uses a source map

### CODE REVIEW

**Comment by jlongster** [comment]
What are those karma errors? I'm sure it's not related, but I haven't seen them before

**Comment by jasonLaster** [comment]
i'm not sure. i might have seen it after london once or twice...

**Comment by jlongster** [comment]
For some reason I don't seem to be able to trigger a rebuild. Do you mind doing that (even by force pushing) and seeing if it's an intermittent?

**Comment by jasonLaster** [comment]
looks intermittent

**Pull request merged**
